languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Thomas Killestein"
copyright = "Thomas Killestein (c) 2025"

[params]
  dateFormat = "2 January 2006"

#   mainSections = ["section1", "section2"]
#   description = "My awesome website"

[params.author]
   name = "Thomas Killestein"
   image = "img/killestein_profile.jpg"
   headline = "Advancing astronomical discovery via collaborative ML"
   bio = "I am a Prize Fellow at the University of Warwick, building next-generation active machine learning for the GOTO survey, and the Kilonova Seekers citizen science project"
   links = [
     { email = "mailto:tom.killestein@gmail.com" },
     { link = "https://tkilleste.in" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/tkillestein" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
     { google-scholar = "https://scholar.google.com/citations?user=jsYLk1MAAAAJ&hl=en" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { mendeley = "https://www.mendeley.com/" },
  #   { microsoft = "https://www.microsoft.com/" },
     { orcid = "https://orcid.org/0000-0002-0440-9597" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { threads = "https://threads.net/@username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { x-twitter = "https://twitter.com/username" },
  #   { youtube = "https://youtube.com/username" },
  #   { xing = "https://xing.com/profile/username" },
   ]
