baseURL = 'https://tkilleste.in'
languageCode = 'en-gb'
title = 'Thomas Killestein'
theme = "risotto"
author = 'Thomas Killestein'
copyright = '(2022) Thomas Killestein'
paginate = 3
enableInlineShortcodes = true
enableGitInfo = true

[params]
[params.theme]
palette = 'nord-dark'
mode = 'dark-mode'


[params.about]
title = "Thomas Killestein"
description = '''
PhD student
University of Warwick
'''

logo = "/images/killestein.jpg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 5 <https://fontawesome.com/> ('fas fa-' or 'fab-fa' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/tkillestein/"

[[params.socialLinks]]
icon = "fas fa-university"
title = "Institutional page"
url = "https://warwick.ac.uk/fac/sci/physics/research/astro/people/thomaskillestein"

[[params.socialLinks]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:t.killestein@warwick.ac.uk"

[[params.socialLinks]]
icon = "ai ai-orcid"
title = "ORCID"
url = "https://orcid.org/0000-0002-0440-9597"

[menu]
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research"
    weight = 2

  [[menu.main]]
    identifier = "papers"
    name = "Papers"
    url = "/papers"
    weight = 6

  [[menu.main]]
    identifier = "conferences-talks"
    name = "Conferences-and-talks"
    url = "/talks"
    weight = 8

  [[menu.main]]
    identifier = "observing"
    name = "Observing"
    url = "/observing"
    weight = 10

[[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]
[privacy.vimeo]
disabled = true
simple = true

[privacy.twitter]
disabled = true
enableDNT = true
simple = true

[privacy.instagram]
disabled = true
simple = true

[privacy.youtube]
disabled = true
privacyEnhanced = true

[privacy.googleAnalytics]
disabled = false
respectDoNotTrack = true
anonymizeIP = true
useSessionStorage = false

[services]
[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true

[server]
[[server.headers]]
  for = '/**'
  [server.headers.values]
    Content-Security-Policy = "base-uri 'self'; connect-src 'self'; default-src 'self'; font-src 'self' https://cdnjs.cloudflare.com?; frame-src 'self'; img-src 'self'; manifest-src 'self'; media-src 'self'; object-src 'none'; script-src 'report-sample' 'self'  https://www.googletagmanager.com/gtag/js; style-src 'report-sample' 'self' https://cdnjs.cloudflare.com; worker-src 'none'"
    Referrer-Policy = 'strict-origin'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'

